spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  datasource:
    url: jdbc:postgresql://localhost:5432/artigo
    username: postgres
    password: sa102101
  jackson:
    deserialization:
      fail-on-unknown-properties: true

